services:

  docker:
    image: docker.io/library/docker:26.0.2
    environment:
      DOCKER_TLS_CERTDIR: ""
    privileged: true
    healthcheck:
      test: /usr/bin/nc -z localhost 2375
      interval: 2s
      start_period: 2s
      retries: 10

  terraform:
    image: docker.io/hashicorp/terraform:1.8
    volumes:
      - ./infrastructure:/var/infrastructure
    working_dir: /var/infrastructure
    depends_on:
      docker:
        condition: service_healthy

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: compose0
